type: RRT_STAR              # ASTAR | DIJKSTRA | RRT_STAR
grid:
  resolution: 0.05
  limits: {x: [-5,5], y: [-5,5], z: [-5,5]}
interpolation: "Quintic"
obstacle_inflation_ratio: 1.5
propagation_distance_m: 0.5
max_iterations: 5000
goal_sample_rate: 0.15
goal_threshold_radius: 0.1
collision_segment_distance: 0.01  #Also min distance for a new node to be added

