type: "2-loop"              
rates_hz:
  inner_loop: 50
  outer_loop: 20
gains:
  outer_loop:
    proportional: {x: 50.0,  y: 50.0,  z: 35.0}
    integral:     {x: 0.0,   y:  0.0,  z: 0.0}
    derivative:   {x: 25.0,  y: 25.0,  z: 8.0}

  inner_loop:
    proportional: {phi: 0.005, theta: 0.005,  psi: 0.0} 
    integral:     {phi: 0.0,   theta: 0.0,    psi: 0.0} 
    derivative:   {phi: 0.05,  theta: 0.05,   psi: 0.0} 
# gains:
#   outer_loop:
#     proportional: {x: 2.56278919e+01,  y: 2.56278919e+01, z: 2.57012684e+00}
#     integral:     {x: 0.0,   y: 0.0,  z: 0.0}
#     derivative:   {x: 1.28994728e+01,  y: 1.28994728e+01, z: 1.08994728e+01}

#   inner_loop:
#     proportional: {phi: 3.74266832e-03,  theta: 3.74266832e-03,  psi: 4.98906794e-03} 
#     integral:     {phi: 0.0, theta: 0.0, psi: 0.0} 
#     derivative:   {phi: 3.20275599e-02,  theta: 3.20275599e-02,  psi: 5.01777145e-02} 

# gains:
#   outer_loop:
#     proportional: {x: 25.5112113,  y: 25.5112113, z: 4.39283609}
#     integral:     {x: 0,   y: 0,  z: 0.05118788}
#     derivative:   {x: 15.37343388,  y: 15.37343388, z: 1.35118532}

#   inner_loop:
#     proportional: {phi: 0.76371426,  theta: 0.76371426,  psi: 0.76371426} 
#     integral:     {phi: 0.0, theta: 0.0, psi: 0.0} 
#     derivative:   {phi: 8.4853864,  theta: 48.4853864,  psi: 8.51397539} 

# PID_Gains  = [[ 12,   0.5,  10],  # Kp_x, Ki_x, Kd_x 
#               [ 12,   0.5,  10],  # y
#               [  4,   0.5,   2],  # z
#               [0.5,  0.05,   4],  # phi
#               [0.5,  0.05,   4],  # theta
#               [  0,     0,   0]]  # psi


# PID_Gains = [[2.56278919e+01, 0., 1.28994728e+01],
#              [2.56278919e+01, 0., 1.28994728e+01],
#              [2.57012684e+00, 0,  8.14091206e-01],
#              [3.74266832e-03, 0.,         3.20275599e-02 ],
#              [3.74266832e-03, 0.,         3.20275599e-02],
#              [4.98906794e-03, 0.,         5.01777145e-02]]