rates_hz: 10
state_cost_multiplier: 10.0
terminal_state_cost_multiplier: 10.0
control_cost_multiplier: 0.1
orientation_cost_multiplier: 0.1  # keeping this value low as current trajectory does not provide inaccurate orientation to track