time:                      # Assumptions: controller_dt ≥ sim_dt, input_delay = delay_time_step*dt, input_delay ≤ controller_dt
  dt: 0.01
  duration: 3.0
  delay_time_step: 0       #input delay, represented as number of time steps after calculating control, to apply the control. Set to 0, for no input delay

quadcopter:
  mass: 0.5
  I_xx: 0.0023
  I_yy: 0.0023
  I_zz: 0.004
  arm_length: 0.175
  motor: {kf: 1, km: 0.0245}
  limits:
    clip_factor: 10   # Max control input represented as clip_factor*quad_weight
    # roll_pitch_rad: 0.6
    # yaw_rate: 3.5
    # thrust_total: [0.0, 18.0]

constants:
  acc_gravity: 9.81

world:
  waypoints:  #List of dictionaries
    - {t: 0.0,  pose: [0.0, 0.0, 1.0,          # Position
                    1.0, 0.0, 0.0, 0.0,        # Orientation (Quaternion -scalar first)
                    0.0, 0.0, 0.0,             # Velocity
                    0.0, 0.0, 0.0 ]}           # Angular Velocity

    - {t: 2.0,  pose: [0.0, 0.0, 3.0,
                    1.0, 0.0, 0.0, 0.0,        
                    0.0, 0.0, 0.0,             
                    0.0, 0.0, 0.0 ]} 

    # - {t: 5.0,  pose: [0.5, 0.0, 1.0,
    #                 1.0, 0.0, 0.0, 0.0,        
    #                 0.0, 0.0, 0.0,             
    #                 0.0, 0.0, 0.0 ]}    

    # - {t: 3.0,  pose: [1.0, 1.0, 2.0,
    #                 1.0, 0.0, 0.0, 0.0,        
    #                 0.0, 0.0, 0.0,             
    #                 0.0, 0.0, 0.0 ]}                             
  wind:
    active: "False"  # |  "True"
    type: "constant" #| "gaussian" | "constant"  #TODO: Try other wind models/variations 
    Cd: 1.0
    speed_vector: [1, 0, 0]    
    std_deviation: [0.05, 0.05, 0.05]

obstacles:
  static:
    - {type: sphere, pose: [5.0, 0.0, 2.0], radius: 0.2}                         #TODO: Handle cases with no objects
      # - {type: box, pose: [2.0, 0.0, 1.0, 0,0,0], size: [0.2, 4.0, 2.0]}




# logging:
#   level: INFO
#   save_telemetry: true
#   out_dir: outputs

# vehicle:
#   mass: 1.25
#   inertia: [0.02, 0.02, 0.04]
#   arm_length: 0.17
#   motor: {kf: 2.3e-6, km: 1.2e-7, max_rpm: 14000}
#   limits:
#     roll_pitch_rad: 0.6
#     yaw_rate: 3.5
#     thrust_total: [0.0, 18.0]

# controller:
#   type: iLQR               # PID | LQR | iLQR | MPC
#   pid:
#     gains:
#       roll:  {kp: 4.0, ki: 0.2, kd: 0.1}
#       pitch: {kp: 4.0, ki: 0.2, kd: 0.1}
#       yaw:   {kp: 2.5, ki: 0.1, kd: 0.05}
#       z:     {kp: 6.0, ki: 0.3, kd: 0.2}
#     loop_rate_hz: 200
#   ilqr:
#     horizon_steps: 50
#     max_iters: 50
#     regularization: {lambda_init: 1.0, lambda_factor: 10.0}
#     line_search: [1.0, 0.5, 0.25, 0.1]
#     constraints: {thrust_min: 0.0, thrust_max: 15.0}




