time:                      # Assumptions: controller_dt ≥ sim_dt, input_delay = delay_time_step*dt, input_delay ≤ controller_dt
  dt: 0.01
  duration: 5
  delay_time_step: 0       #input delay, represented as number of time steps after calculating control, to apply the control. Set to 0, for no input delay

quadcopter:
  mass: 0.5
  I_xx: 0.0023
  I_yy: 0.0023
  I_zz: 0.004
  arm_length: 0.175
  motor: {kf: 1, km: 0.0245}
  limits:
    clip_factor: 20   # Max control input represented as clip_factor*quad_weight

constants:
  acc_gravity: 9.81

world:
  waypoints:  #List of dictionaries
    - {t: 0.0,  pose: [0.0, 0.0, 1.0,          # Position
                    1.0, 0.0, 0.0, 0.0,        # Orientation (Quaternion -scalar first)
                    0.0, 0.0, 0.0,             # Velocity
                    0.0, 0.0, 0.0 ]}           # Angular Velocity

    - {t: 2.0,  pose: [1.0, 1.0, 2.0,  
                    1.0, 0.0, 0.0, 0.0,        
                    0.0, 0.0, 0.0,             
                    0.0, 0.0, 0.0 ]} 

    - {t: 4.0,  pose: [2.0, 0.0, 1.0,  
                    1.0, 0.0, 0.0, 0.0,        
                    0.0, 0.0, 0.0,             
                    0.0, 0.0, 0.0 ]}    

          
  wind:
    active: "False"  # |  "True"
    type: "constant" #| "gaussian" | "constant"  #TODO: Try other wind models/variations 
    Cd: 1.0
    speed_vector: [1, 0, 0]    
    std_deviation: [0.05, 0.05, 0.05]

obstacles:
  static:
    - {type: sphere, pose: [1.0, 1.0, 2.5], radius: 0.2}                         #TODO: Handle cases with no objects
    - {type: sphere, pose: [1.0, 0.5, 2], radius: 0.2}                         
    - {type: sphere, pose: [1.0, 1.5, 2], radius: 0.2}      
    - {type: sphere, pose: [1.0, 1.0, 1.5], radius: 0.2}     
    - {type: sphere, pose: [1.5, 0.0, 1.0], radius: 0.2}                         
    - {type: sphere, pose: [2.5, 0.0, 1.0], radius: 0.2}                         
    - {type: sphere, pose: [2.0, 0.5, 1.0], radius: 0.2}      
    - {type: sphere, pose: [2.0, -0.5, 1.0], radius: 0.2}                      
      # - {type: box, pose: [2.0, 0.0, 1.0, 0,0,0], size: [0.2, 4.0, 2.0]}




# logging:
#   level: INFO
#   save_telemetry: true
#   out_dir: outputs








